### ISSUE TITLE
[Bug]: gdxtest4 crashing on macOS

### ISSUE THREAD

**Issue by Azhrei** [thelsing/maptool#135]
### Describe the Bug

Splash screen appears, then about 3s later, the app crashes.

### To Reproduce

Extract the app from the .dmg, unquarantine it, and run it.

### Expected Behaviour

The main window appears after the splash screen.

### MapTool Info

gdxtest4

### Desktop

macOS Big Sur (latest)

### Additional Context

The crash dump collected by Apple's automated tool is attached (couldn't paste it as it's too large).
[crash-report.txt](https://github.com/thelsing/maptool/files/9160157/crash-report.txt)

**Comment by Azhrei** [comment]
I tried loading the Nerps 1.5.2 D&D3.5/PF1 campaign and got this error in the log:
```
2022-07-21 11:51:16.687 INFO  net.rptools.maptool.client.MapTool - ********************************************************************************
2022-07-21 11:51:16.847 INFO  net.rptools.maptool.client.MapTool - **                                                                            **
2022-07-21 11:51:16.847 INFO  net.rptools.maptool.client.MapTool - **                              MapTool Started!                              **
2022-07-21 11:51:16.848 INFO  net.rptools.maptool.client.MapTool - **                                                                            **
2022-07-21 11:51:16.848 INFO  net.rptools.maptool.client.MapTool - ********************************************************************************
2022-07-21 11:51:16.848 INFO  net.rptools.maptool.client.MapTool - Logging to: /Users/franke/.maptool-rptools/logs/maptool.log
2022-07-21 11:51:16.849 INFO  net.rptools.maptool.client.MapTool - getting MapTool version from manifest: gdxtest4
2022-07-21 11:51:16.849 INFO  net.rptools.maptool.client.MapTool - getting MapTool vendor from manifest:  RPTools
2022-07-21 11:51:16.901 INFO  net.rptools.maptool.client.MapTool - argument passed via command line: -v=0.0.1
2022-07-21 11:51:16.901 INFO  net.rptools.maptool.client.MapTool - overriding MapTool version from command line to: 0.0.1
2022-07-21 11:51:16.902 INFO  net.rptools.maptool.client.MapTool - MapTool vendor: RPTools
2022-07-21 11:51:17.917 INFO  net.rptools.maptool.client.AppSetup - Installing ui theme: /Users/franke/.maptool-rptools/themes/ui/Default.theme
2022-07-21 11:51:17.919 INFO  net.rptools.maptool.client.AppSetup - Installing ui theme: /Users/franke/.maptool-rptools/themes/ui/RT_Default_Dark.theme
2022-07-21 11:51:17.920 INFO  net.rptools.maptool.client.AppSetup - Installing ui theme: /Users/franke/.maptool-rptools/themes/ui/MT_Flat_Green_Sans_13.theme
2022-07-21 11:51:17.921 INFO  net.rptools.maptool.client.AppSetup - Installing ui theme: /Users/franke/.maptool-rptools/themes/ui/RT_Flat_Default_Green.theme
2022-07-21 11:51:17.922 INFO  net.rptools.maptool.client.AppSetup - Installing ui theme: /Users/franke/.maptool-rptools/themes/ui/TL_Golden_Sans_13.theme
2022-07-21 11:51:17.923 INFO  net.rptools.maptool.client.AppSetup - Installing ui theme: /Users/franke/.maptool-rptools/themes/ui/TL_Forest_Sans_11.theme
2022-07-21 11:51:17.924 INFO  net.rptools.maptool.client.AppSetup - Installing ui theme: /Users/franke/.maptool-rptools/themes/ui/TL_Forest_Sans_13.theme
2022-07-21 11:51:17.925 INFO  net.rptools.maptool.client.AppSetup - Installing ui theme: /Users/franke/.maptool-rptools/themes/ui/TL_Golden_Sans_11.theme
2022-07-21 11:51:18.106 INFO  net.rptools.maptool.client.AppUpdate - Implementation-Version from Manifest: gdxtest4
2022-07-21 11:51:18.107 INFO  net.rptools.maptool.client.AppUpdate - Cleaned version: 4
2022-07-21 11:51:22.489 INFO  net.rptools.maptool.server.ClientHandshake - Anonymous User :send: CLIENT_INIT_MSG
2022-07-21 11:51:22.509 INFO  net.rptools.maptool.server.ServerHandshake - 127.0.0.1-0 :got: CLIENT_INIT_MSG
2022-07-21 11:51:22.521 INFO  net.rptools.maptool.server.ServerHandshake - 127.0.0.1-0 :send: USE_AUTH_TYPE_MSG
2022-07-21 11:51:22.523 INFO  net.rptools.maptool.server.ClientHandshake - Anonymous User :got: USE_AUTH_TYPE_MSG
2022-07-21 11:51:22.525 INFO  net.rptools.maptool.server.ClientHandshake - Anonymous User :send: CLIENT_AUTH_MESSAGE
2022-07-21 11:51:22.526 INFO  net.rptools.maptool.server.ServerHandshake - 127.0.0.1-0 :got: CLIENT_AUTH_MESSAGE
2022-07-21 11:51:22.545 INFO  net.rptools.maptool.server.ServerHandshake - 127.0.0.1-0 :send: CONNECTION_SUCCESSFUL_MSG
2022-07-21 11:51:22.546 INFO  net.rptools.maptool.server.ClientHandshake - Anonymous User :got: CONNECTION_SUCCESSFUL_MSG
2022-07-21 11:51:22.604 INFO  net.rptools.maptool.client.ClientMessageHandler - Anonymous User: p got: PLAYER_CONNECTED_MSG
2022-07-21 11:51:22.606 INFO  net.rptools.maptool.client.ClientMessageHandler - Anonymous User: p got: PLAYER_CONNECTED_MSG
2022-07-21 11:51:22.752 INFO  net.rptools.maptool.client.ClientMessageHandler - Anonymous User: p got: SET_CAMPAIGN_MSG
2022-07-21 11:51:48.310 ERROR net.rptools.maptool.client.MapTool - Could not load campaign.
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Unknown Source) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Unknown Source) ~[?:?]
	at java.util.Objects.checkIndex(Unknown Source) ~[?:?]
	at java.util.ArrayList.set(Unknown Source) ~[?:?]
	at com.google.protobuf.LazyStringArrayList.set(LazyStringArrayList.java:140) ~[protobuf-java-3.20.0.jar:?]
	at com.google.protobuf.LazyStringArrayList.set(LazyStringArrayList.java:61) ~[protobuf-java-3.20.0.jar:?]
	at net.rptools.maptool.server.proto.BarTokenOverlayDto$Builder.setAssetIds(BarTokenOverlayDto.java:1256) ~[MapTool.jar:gdxtest4]
	at net.rptools.maptool.client.ui.token.SingleImageBarTokenOverlay.toDto(SingleImageBarTokenOverlay.java:152) ~[MapTool.jar:gdxtest4]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.util.Iterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
	at net.rptools.maptool.model.CampaignProperties.toDto(CampaignProperties.java:502) ~[MapTool.jar:gdxtest4]
	at net.rptools.maptool.model.Campaign.toDto(Campaign.java:761) ~[MapTool.jar:gdxtest4]
	at net.rptools.maptool.client.ServerCommandClientImpl.setCampaign(ServerCommandClientImpl.java:78) ~[MapTool.jar:gdxtest4]
	at net.rptools.maptool.client.AppActions$CampaignLoader.done(AppActions.java:2651) ~[MapTool.jar:gdxtest4]
	at javax.swing.SwingWorker$5.run(Unknown Source) ~[?:?]
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source) ~[?:?]
	at sun.swing.AccumulativeRunnable.run(Unknown Source) ~[?:?]
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source) ~[?:?]
	at javax.swing.Timer.fireActionPerformed(Unknown Source) ~[?:?]
	at javax.swing.Timer$DoPostEvent.run(Unknown Source) ~[?:?]
	at java.awt.event.InvocationEvent.dispatch(Unknown Source) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) ~[?:?]
	at java.awt.EventQueue$4.run(Unknown Source) ~[?:?]
	at java.awt.EventQueue$4.run(Unknown Source) ~[?:?]
	at java.security.AccessController.doPrivileged(Unknown Source) [?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [?:?]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) [?:?]
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:54) [MapTool.jar:gdxtest4]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.run(Unknown Source) [?:?]
```

**Comment by thelsing** [comment]
I'm confused. It does start now, but some campaing file fails to open?

**Comment by thelsing** [comment]
The array out of bounds issue should be addressed with rptools/maptool#3509.

**Comment by Azhrei** [comment]
> I'm confused. It does start now, but some campaing file fails to open?

Correct.

I haven't tried any of my _really_ involved campaign files, but I'll get to that later this afternoon, I hope.

If you want the campaign file, I can provide it (it's pretty large), but I'm not sure that would necessarily help you much at this point...?

**Comment by thelsing** [comment]
I created gdxtest5 with the fix. So this file should load now. Let me know if anything else comes up.
